### DISCUSSION TITLE
Allow users to mention that they're training an ML model that will be posted on HuggingFace.

### DISCUSSION THREAD

**Discussion by selenecodes** [mlco2/codecarbon#566] [Ideas]
HuggingFace is used to publish many large models and I've noticed that a lot of models that publish their CO2 metrics copy the output from codecarbon 1:1. This is incorrect since codecarbon outputs kg/co2e whilst [huggingface expects g/co2e.](https://huggingface.co/docs/hub/en/model-cards-co2)

Would it be possible to either warn the user or convert the metric automatically by providing a toggle in the config asking the user whether they're training an ML model and wish to publish to huggingface?

**Comment by SaboniAmine** [comment]
This might interest @sashavor ?

**Comment by sashavor** [comment]
Interesting point! I agree that it can be confusing. Maybe we can see if we can directly upload the codecarbon output CSV alongside a model, so the information gets input automatically?

**Comment by selenecodes** [comment]
I must confess I haven't worked much with codecarbon before but I do know that HF expects the output to be in the frontmatter of the `README.md` so I think the most beautiful solution would be to ask the user if they'd be okay with auto-inserting it into the markdown if such a toggle did exist and was checked by the user.

Example of HF CO2 frontmatter section below:
```
---
co2_eq_emissions:
  emissions: number (in grams of CO2)
  source: "source of the information, either directly from AutoTrain, code carbon or from a scientific article documenting the model"
  training_type: "pre-training or fine-tuning"
  geographical_location: "as granular as possible, for instance Quebec, Canada or Brooklyn, NY, USA. To check your compute's electricity grid, you can check out https://app.electricitymap.org."
  hardware_used: "how much compute and what kind, e.g. 8 v100 GPUs"
---
```
